version: '3.8'

services:
  meuProjeto:
    image: descomplicaseapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
